spring.application.name=teste-tinnova-java
server.port=3000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/tinnova-db
spring.datasource.username=admin
spring.datasource.password=admin
api.security.token.secret=tinnova
spring.data.redis.host=localhost
spring.data.redis.port=6379
logging.level.org.springframework.security=DEBUG